version: '3.9'
services:
  db:
    # image: postgres:16-alpine
    image: postgresai/extended-postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./datasets:/mnt/datasets
volumes:
  db:
    driver: local
